apiVersion: v1
kind: ServiceAccount
metadata:
  name: upkube-sa
  namespace: default

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: upkube-sa
  namespace: default
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io


--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: upkube
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upkube
  template:
    metadata:
      labels:
        app: upkube
    spec:
      serviceAccountName: upkube-sa
      containers:
      - name: upkube
        image: upkube:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: upkube
  namespace: default
spec:
  selector:
    app: upkube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
