name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Set outputs
        id: vars
        run: echo "::set-output name=latest_tag::$(git describe --tags --abbrev=0)"

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.latest_tag }}

      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: build docker image
        run: |
          docker build -t ghcr.io/kunalsin9h/upkube:latest .

      - name: push docker images
        run: |
          echo "${{ secrets.GHCR }}" | docker login ghcr.io -u "kunalsin9h" --password-stdin
          docker push ghcr.io/kunalsin9h/upkube:latest

          docker tag ghcr.io/kunalsin9h/upkube:latest ghcr.io/kunalsin9h/upkube:${{ steps.vars.outputs.latest_tag }} 
          docker push ghcr.io/kunalsin9h/upkube:${{ steps.vars.outputs.latest_tag }} 
          